//! Emits, for every message of the proto, an OpenRTB JSON codec
//! (`serde::Deserialize` + `crate::json::OpenRtbJson`) and getters for fields
//! that declare a spec default (`[default = …]`, which buffa ignores).
//!
//! The JSON follows OpenRTB conventions, not proto3 canonical JSON: original
//! snake_case names, integer enums, booleans as 0/1, `ext` objects whose
//! unknown keys are kept verbatim.

use std::fmt::Write;

use buffa_codegen::context::CodeGenContext;
use buffa_codegen::idents::make_field_ident;
use buffa_descriptor::generated::descriptor::field_descriptor_proto::{Label, Type};
use buffa_descriptor::generated::descriptor::{
    DescriptorProto, FieldDescriptorProto, FileDescriptorProto,
};

/// Scalar representation shared by decoding (`Lenient<T>`) and encoding (`write_*`).
#[derive(Clone, Copy, PartialEq)]
enum Scalar {
    Str,
    I32,
    I64,
    U32,
    U64,
    F32,
    F64,
    Bool,
}

impl Scalar {
    fn rust(self) -> &'static str {
        match self {
            Scalar::Str => "::std::string::String",
            Scalar::I32 => "i32",
            Scalar::I64 => "i64",
            Scalar::U32 => "u32",
            Scalar::U64 => "u64",
            Scalar::F32 => "f32",
            Scalar::F64 => "f64",
            Scalar::Bool => "bool",
        }
    }

    fn writer(self) -> &'static str {
        match self {
            Scalar::Str => "crate::json::write_str",
            Scalar::I32 | Scalar::I64 | Scalar::U32 | Scalar::U64 => "crate::json::write_int",
            Scalar::F32 => "crate::json::write_f32",
            Scalar::F64 => "crate::json::write_f64",
            Scalar::Bool => "crate::json::write_bool",
        }
    }
}

enum Kind {
    Scalar(Scalar),
    Enum,
    /// Message type: Rust path. `passthrough` = google.protobuf.Value & co, serialized by serde.
    Msg {
        path: String,
        passthrough: bool,
    },
    Map {
        key: Scalar,
        value: Scalar,
    },
}

struct Field<'a> {
    desc: &'a FieldDescriptorProto,
    name: &'a str,
    ident: String,
    kind: Kind,
    repeated: bool,
}

struct Oneof<'a> {
    ident: String,
    enum_path: String,
    members: Vec<Field<'a>>,
}

pub fn generate(
    ctx: &CodeGenContext,
    files: &[FileDescriptorProto],
    to_generate: &[String],
) -> String {
    let mut out = String::from(
        "// @generated by openrtb-codegen. DO NOT EDIT.\n\
         // OpenRTB JSON codec and spec-default getters for the buffa model.\n\n",
    );
    for file in files
        .iter()
        .filter(|f| f.name.as_ref().is_some_and(|n| to_generate.contains(n)))
    {
        let package = file.package.as_deref().unwrap_or_default();
        for msg in &file.message_type {
            gen_message(ctx, &mut out, package, &format!(".{package}"), msg);
        }
    }
    out
}

fn gen_message(
    ctx: &CodeGenContext,
    out: &mut String,
    package: &str,
    parent_fqn: &str,
    msg: &DescriptorProto,
) {
    let name = msg.name.as_deref().unwrap();
    let fqn = format!("{parent_fqn}.{name}");
    for nested in &msg.nested_type {
        if !nested
            .options
            .as_option()
            .and_then(|o| o.map_entry)
            .unwrap_or(false)
        {
            gen_message(ctx, out, package, &fqn, nested);
        }
    }

    let path = rust_path(ctx, &fqn);

    let mut fields = Vec::new();
    let mut oneofs: Vec<Oneof> = Vec::new();
    for (idx, decl) in msg.oneof_decl.iter().enumerate() {
        let members: Vec<_> = msg
            .field
            .iter()
            .filter(|f| f.oneof_index == Some(idx as i32) && !f.proto3_optional.unwrap_or(false))
            .map(|f| field(ctx, msg, &fqn, f))
            .collect();
        if members.is_empty() {
            continue;
        }
        let oneof_name = decl.name.as_deref().unwrap();
        oneofs.push(Oneof {
            ident: make_field_ident(oneof_name).to_string(),
            enum_path: format!(
                "{}::{}",
                oneof_module(ctx, package, &fqn),
                to_pascal_case(oneof_name)
            ),
            members,
        });
    }
    for f in &msg.field {
        let in_oneof = f.oneof_index.is_some() && !f.proto3_optional.unwrap_or(false);
        if !in_oneof {
            fields.push(field(ctx, msg, &fqn, f));
        }
    }

    gen_deserialize(out, name, &path, &fields, &oneofs);
    gen_encode(out, name, &path, &fields, &oneofs);
    gen_defaults(out, &path, &fields);
}

fn field<'a>(
    ctx: &CodeGenContext,
    msg: &DescriptorProto,
    msg_fqn: &str,
    f: &'a FieldDescriptorProto,
) -> Field<'a> {
    let name = f.name.as_deref().unwrap();
    let ty = f.r#type.unwrap();
    let repeated = f.label == Some(Label::LABEL_REPEATED);
    let kind = match scalar(ty) {
        Some(s) => Kind::Scalar(s),
        None => match ty {
            Type::TYPE_ENUM => Kind::Enum,
            Type::TYPE_MESSAGE => {
                let type_name = f.type_name.as_deref().unwrap();
                let entry = type_name
                    .strip_prefix(msg_fqn)
                    .and_then(|rest| rest.strip_prefix('.'))
                    .and_then(|local| {
                        msg.nested_type
                            .iter()
                            .find(|n| n.name.as_deref() == Some(local))
                    })
                    .filter(|n| {
                        n.options
                            .as_option()
                            .and_then(|o| o.map_entry)
                            .unwrap_or(false)
                    });
                match entry {
                    Some(entry) => Kind::Map {
                        key: scalar(entry.field[0].r#type.unwrap()).expect("scalar map key"),
                        value: scalar(entry.field[1].r#type.unwrap()).expect("scalar map value"),
                    },
                    None => Kind::Msg {
                        path: rust_path(ctx, type_name),
                        passthrough: type_name.starts_with(".google.protobuf."),
                    },
                }
            }
            other => panic!("unsupported field type {other:?} for {msg_fqn}.{name}"),
        },
    };
    // Map fields are `repeated Entry` in the descriptor but a single JSON object.
    let repeated = repeated && !matches!(kind, Kind::Map { .. });
    Field {
        desc: f,
        name,
        ident: make_field_ident(name).to_string(),
        kind,
        repeated,
    }
}

fn scalar(ty: Type) -> Option<Scalar> {
    Some(match ty {
        Type::TYPE_STRING => Scalar::Str,
        Type::TYPE_INT32 | Type::TYPE_SINT32 | Type::TYPE_SFIXED32 => Scalar::I32,
        Type::TYPE_INT64 | Type::TYPE_SINT64 | Type::TYPE_SFIXED64 => Scalar::I64,
        Type::TYPE_UINT32 | Type::TYPE_FIXED32 => Scalar::U32,
        Type::TYPE_UINT64 | Type::TYPE_FIXED64 => Scalar::U64,
        Type::TYPE_FLOAT => Scalar::F32,
        Type::TYPE_DOUBLE => Scalar::F64,
        Type::TYPE_BOOL => Scalar::Bool,
        _ => return None,
    })
}

fn rust_path(ctx: &CodeGenContext, fqn: &str) -> String {
    let path = ctx
        .rust_type(fqn)
        .or_else(|| ctx.rust_type(fqn.trim_start_matches('.')))
        .unwrap_or_else(|| panic!("no rust type for {fqn}"));
    if path.starts_with("::") || path.starts_with("crate::") {
        path.to_owned()
    } else {
        format!("crate::{path}")
    }
}

/// `crate::<pkg>::__buffa::oneof::<msg modules>` for the oneof enums of message `fqn`.
fn oneof_module(ctx: &CodeGenContext, package: &str, fqn: &str) -> String {
    let full = rust_path(ctx, fqn);
    let pkg_mod = format!("crate::{}", package.replace('.', "::"));
    let within = full
        .strip_prefix(&format!("{pkg_mod}::"))
        .expect("message in its package");
    let mut segs: Vec<String> = within.split("::").map(str::to_owned).collect();
    let last = segs.pop().unwrap();
    segs.push(to_snake_case(&last));
    format!("{pkg_mod}::__buffa::oneof::{}", segs.join("::"))
}

/// `"name":` as a byte-string literal.
fn key_lit(name: &str) -> String {
    format!("b\"\\\"{name}\\\":\"")
}

/// A oneof `{x: string, x_native: message}` pair reads/writes both under key `x`.
fn str_or_msg_pair<'o>(o: &'o Oneof) -> Option<(&'o Field<'o>, &'o Field<'o>)> {
    let s = o
        .members
        .iter()
        .find(|f| matches!(f.kind, Kind::Scalar(Scalar::Str)))?;
    let m = o
        .members
        .iter()
        .find(|f| matches!(f.kind, Kind::Msg { .. }) && f.name == format!("{}_native", s.name))?;
    Some((s, m))
}

fn is_native_root(name: &str) -> bool {
    name == "NativeRequest" || name == "NativeResponse"
}

fn gen_deserialize(out: &mut String, name: &str, path: &str, fields: &[Field], oneofs: &[Oneof]) {
    let mut arms = String::new();
    for f in fields {
        let id = &f.ident;
        let key = f.name;
        let expr = match (&f.kind, f.repeated) {
            (Kind::Scalar(s), false) => format!(
                "m.{id} = map.next_value::<crate::json::Lenient<{}>>()?.0;",
                s.rust()
            ),
            (Kind::Scalar(s), true) => format!(
                "m.{id} = map.next_value::<crate::json::LenientVec<{}>>()?.0;",
                s.rust()
            ),
            (Kind::Enum, false) => {
                format!(
                    "m.{id} = map.next_value::<crate::json::Lenient<i32>>()?.0.map(::buffa::EnumValue::from);"
                )
            }
            (Kind::Enum, true) => format!(
                "m.{id} = map.next_value::<crate::json::LenientVec<i32>>()?.0.into_iter().map(::buffa::EnumValue::from).collect();"
            ),
            (
                Kind::Msg {
                    passthrough: true,
                    path,
                },
                false,
            ) => format!(
                "if let ::core::option::Option::Some(v) = map.next_value::<::core::option::Option<{path}>>()? {{ m.{id} = ::buffa::MessageField::some(v); }}"
            ),
            (
                Kind::Msg {
                    passthrough: true,
                    path,
                },
                true,
            ) => format!(
                "m.{id} = map.next_value::<::core::option::Option<::std::vec::Vec<{path}>>>()?.unwrap_or_default();"
            ),
            (Kind::Msg { .. }, false) => format!(
                "if !map.next_value_seed(crate::json::Fill(m.{id}.get_or_insert_default()))? {{ m.{id} = ::buffa::MessageField::none(); }}"
            ),
            (Kind::Msg { .. }, true) => {
                format!("map.next_value_seed(crate::json::FillVec(&mut m.{id}))?;")
            }
            (Kind::Map { key: k, value: v }, _) => format!(
                "m.{id} = map.next_value::<::core::option::Option<::std::collections::BTreeMap<{}, crate::json::Lenient<{}>>>>()?.unwrap_or_default().into_iter().filter_map(|(k, v)| v.0.map(|v| (k, v))).collect();",
                k.rust(),
                v.rust()
            ),
        };
        writeln!(arms, "\"{key}\" => {{ {expr} }}").unwrap();
    }
    for o in oneofs {
        let pair = str_or_msg_pair(o);
        for f in &o.members {
            let variant = to_pascal_case(f.name);
            let (oid, epath) = (&o.ident, &o.enum_path);
            if let Some((s, msg)) = pair {
                if f.name == s.name {
                    let Kind::Msg { path: mpath, .. } = &msg.kind else {
                        unreachable!()
                    };
                    let mvariant = to_pascal_case(msg.name);
                    writeln!(
                        arms,
                        "\"{key}\" => {{ m.{oid} = match map.next_value::<crate::json::StrOrMsg<{mpath}>>()? {{ \
                         crate::json::StrOrMsg::Str(s) => ::core::option::Option::Some({epath}::{variant}(s)), \
                         crate::json::StrOrMsg::Msg(v) => ::core::option::Option::Some({epath}::{mvariant}(::std::boxed::Box::new(v))), \
                         crate::json::StrOrMsg::Null => m.{oid}.take(), }}; }}",
                        key = s.name
                    )
                    .unwrap();
                    continue;
                }
            }
            let expr = match &f.kind {
                Kind::Scalar(s) => format!(
                    "if let ::core::option::Option::Some(v) = map.next_value::<crate::json::Lenient<{}>>()?.0 {{ m.{oid} = ::core::option::Option::Some({epath}::{variant}(v)); }}",
                    s.rust()
                ),
                Kind::Enum => format!(
                    "if let ::core::option::Option::Some(v) = map.next_value::<crate::json::Lenient<i32>>()?.0 {{ m.{oid} = ::core::option::Option::Some({epath}::{variant}(::buffa::EnumValue::from(v))); }}"
                ),
                Kind::Msg {
                    passthrough: true,
                    path,
                } => format!(
                    "if let ::core::option::Option::Some(v) = map.next_value::<::core::option::Option<{path}>>()? {{ m.{oid} = ::core::option::Option::Some({epath}::{variant}(::std::boxed::Box::new(v))); }}"
                ),
                Kind::Msg { path, .. } => format!(
                    "let mut v = ::std::boxed::Box::<{path}>::default(); if map.next_value_seed(crate::json::Fill(&mut *v))? {{ m.{oid} = ::core::option::Option::Some({epath}::{variant}(v)); }}"
                ),
                Kind::Map { .. } => unreachable!("maps cannot be oneof members"),
            };
            writeln!(arms, "\"{}\" => {{ {expr} }}", f.name).unwrap();
        }
    }
    let native_wrapper = if is_native_root(name) {
        // Native 1.0 wraps the object: `{"native": {...}}`.
        "\"native\" => { if map.next_value_seed(crate::json::Fill(&mut *m))? { crate::json::set_native_wrapper(&mut m.__buffa_unknown_fields); } }"
    } else {
        ""
    };
    let fallback = format!("{native_wrapper}\n_ => {{ unknown.capture(&key, &mut map)?; }}");
    let raw_init = "let mut unknown = crate::json::UnknownKeys::default();";
    let raw_finish = "unknown.finish(&mut m.__buffa_unknown_fields);";
    let _ = name;
    write!(
        out,
        r#"
impl crate::json::JsonFill for {path} {{
    #[allow(unused_mut)]
    fn fill<'de, A: ::serde::de::MapAccess<'de>>(&mut self, mut map: A) -> ::core::result::Result<(), A::Error> {{
        let m = self;
        {raw_init}
        while let ::core::option::Option::Some(key) = map.next_key::<crate::json::Key<'de>>()? {{
            match &*key {{
                {arms}
                {fallback}
            }}
        }}
        {raw_finish}
        ::core::result::Result::Ok(())
    }}
}}

impl<'de> ::serde::Deserialize<'de> for {path} {{
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> ::core::result::Result<Self, D::Error> {{
        crate::json::deserialize_filled(deserializer)
    }}
}}
"#
    )
    .unwrap();
}

fn gen_encode(out: &mut String, name: &str, path: &str, fields: &[Field], oneofs: &[Oneof]) {
    let mut body = String::new();
    for f in fields {
        let id = &f.ident;
        let key = key_lit(f.name);
        let stmt = match (&f.kind, f.repeated) {
            (Kind::Scalar(s), false) => {
                let deref = if *s == Scalar::Str { "v" } else { "*v" };
                format!(
                    "if let ::core::option::Option::Some(v) = &self.{id} {{ w.key({key}); {}(w.out, {deref}); }}",
                    s.writer()
                )
            }
            (Kind::Scalar(s), true) => {
                let deref = if *s == Scalar::Str { "v" } else { "*v" };
                format!(
                    "if !self.{id}.is_empty() {{ w.key({key}); crate::json::write_array(w.out, &self.{id}, |out, v| {}(out, {deref})); }}",
                    s.writer()
                )
            }
            (Kind::Enum, false) => format!(
                "if let ::core::option::Option::Some(v) = &self.{id} {{ w.key({key}); crate::json::write_int(w.out, v.to_i32()); }}"
            ),
            (Kind::Enum, true) => format!(
                "if !self.{id}.is_empty() {{ w.key({key}); crate::json::write_array(w.out, &self.{id}, |out, v| crate::json::write_int(out, v.to_i32())); }}"
            ),
            (
                Kind::Msg {
                    passthrough: true, ..
                },
                false,
            ) => format!(
                "if let ::core::option::Option::Some(v) = self.{id}.as_option() {{ w.key({key}); crate::json::write_serde(w.out, v); }}"
            ),
            (
                Kind::Msg {
                    passthrough: true, ..
                },
                true,
            ) => format!(
                "if !self.{id}.is_empty() {{ w.key({key}); crate::json::write_array(w.out, &self.{id}, |out, v| crate::json::write_serde(out, v)); }}"
            ),
            (Kind::Msg { .. }, false) => format!(
                "if let ::core::option::Option::Some(v) = self.{id}.as_option() {{ w.key({key}); crate::json::OpenRtbJson::write_json(v, w.out); }}"
            ),
            (Kind::Msg { .. }, true) => format!(
                "if !self.{id}.is_empty() {{ w.key({key}); crate::json::write_array(w.out, &self.{id}, |out, v| crate::json::OpenRtbJson::write_json(v, out)); }}"
            ),
            (Kind::Map { key: k, value: v }, _) => {
                let kw = if *k == Scalar::Str {
                    "crate::json::write_str(out, k)".to_owned()
                } else {
                    "crate::json::write_key_int(out, *k)".to_owned()
                };
                let vderef = if *v == Scalar::Str { "v" } else { "*v" };
                format!(
                    "if !self.{id}.is_empty() {{ w.key({key}); crate::json::write_map(w.out, self.{id}.iter(), |out, k| {kw}, |out, v| {}(out, {vderef})); }}",
                    v.writer()
                )
            }
        };
        writeln!(body, "{stmt}").unwrap();
    }
    for o in oneofs {
        let pair = str_or_msg_pair(o);
        let mut arms = String::new();
        for f in &o.members {
            let variant = to_pascal_case(f.name);
            let key_name = match pair {
                Some((s, m)) if f.name == m.name => s.name,
                _ => f.name,
            };
            let key = key_lit(key_name);
            let write = match &f.kind {
                Kind::Scalar(Scalar::Str) => format!("{}(w.out, v)", Scalar::Str.writer()),
                Kind::Scalar(s) => format!("{}(w.out, *v)", s.writer()),
                Kind::Enum => "crate::json::write_int(w.out, v.to_i32())".to_owned(),
                Kind::Msg {
                    passthrough: true, ..
                } => "crate::json::write_serde(w.out, &**v)".to_owned(),
                Kind::Msg { .. } => "crate::json::OpenRtbJson::write_json(&**v, w.out)".to_owned(),
                Kind::Map { .. } => unreachable!(),
            };
            writeln!(
                arms,
                "::core::option::Option::Some({}::{variant}(v)) => {{ w.key({key}); {write}; }}",
                o.enum_path
            )
            .unwrap();
        }
        writeln!(
            body,
            "match &self.{} {{ {arms} ::core::option::Option::None => {{}} }}",
            o.ident
        )
        .unwrap();
    }
    body.push_str("crate::json::write_unknown_keys(&mut w, &self.__buffa_unknown_fields);\n");
    let (wrap_open, wrap_close) = if is_native_root(name) {
        (
            "let wrapped = crate::json::has_native_wrapper(&self.__buffa_unknown_fields); if wrapped { out.extend_from_slice(b\"{\\\"native\\\":\"); }",
            "if wrapped { out.push(b'}'); }",
        )
    } else {
        ("", "")
    };
    write!(
        out,
        r#"
impl crate::json::OpenRtbJson for {path} {{
    fn write_json(&self, out: &mut ::std::vec::Vec<u8>) {{
        {wrap_open}
        let mut w = crate::json::ObjWriter::new(&mut *out);
        {body}
        w.end();
        {wrap_close}
    }}
}}
"#
    )
    .unwrap();
}

fn gen_defaults(out: &mut String, path: &str, fields: &[Field]) {
    let mut getters = String::new();
    for f in fields.iter().filter(|f| !f.repeated) {
        let Some(default) = f.desc.default_value.as_deref() else {
            continue;
        };
        let id = &f.ident;
        let name = f.name;
        let doc = format!("/// `{name}`, or its OpenRTB default (`{default}`) when absent.");
        let getter = match &f.kind {
            Kind::Scalar(Scalar::Str) => {
                format!(
                    "{doc}\npub fn {id}(&self) -> &str {{ self.{id}.as_deref().unwrap_or({default:?}) }}"
                )
            }
            Kind::Scalar(Scalar::Bool) => {
                format!("{doc}\npub fn {id}(&self) -> bool {{ self.{id}.unwrap_or({default}) }}")
            }
            Kind::Scalar(s @ (Scalar::F32 | Scalar::F64)) => {
                let lit = if default.contains('.') || default.contains('e') {
                    default.to_owned()
                } else {
                    format!("{default}.0")
                };
                format!(
                    "{doc}\npub fn {id}(&self) -> {} {{ self.{id}.unwrap_or({lit}) }}",
                    s.rust()
                )
            }
            Kind::Scalar(s) => format!(
                "{doc}\npub fn {id}(&self) -> {} {{ self.{id}.unwrap_or({default}) }}",
                s.rust()
            ),
            // Enum defaults name a value; no OpenRTB field needs them yet.
            _ => continue,
        };
        writeln!(getters, "{getter}").unwrap();
    }
    if !getters.is_empty() {
        write!(out, "\nimpl {path} {{\n{getters}}}\n").unwrap();
    }
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

/// Same rules as buffa-codegen's module naming (`XMLHttp` → `xml_http`).
fn to_snake_case(s: &str) -> String {
    let chars: Vec<char> = s.chars().collect();
    let mut result = String::with_capacity(s.len() + 4);
    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() && i > 0 {
            let prev = chars[i - 1];
            let next_is_lower = chars.get(i + 1).is_some_and(|n| n.is_lowercase());
            if prev.is_lowercase() || (prev.is_uppercase() && next_is_lower) {
                result.push('_');
            }
        }
        result.extend(c.to_lowercase());
    }
    result
}
