[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/lapoule/rust-openrtb"

[workspace.dependencies]
buffa = "0.9.2"
buffa-types = "0.9.2"
buffa-build = "0.9.2"

[profile.bench]
lto = true
codegen-units = 1
