//! OpenRTB 2.6 model generated from the official IAB `openrtb.proto`.
//!
//! - Protobuf: owned types, zero-copy views and lazy views, by buffa.
//! - JSON: OpenRTB conventions (see [`json`]), generated by `openrtb-codegen`.
//!
//! Regenerate with `cargo xtask codegen`.

// buffa's generated tree (`pub mod com { … }`), at the crate root so that
// `crate::com::…` paths in the generated JSON codec resolve.
include!("generated/buffa/mod.rs");

pub use openrtb_json as json;

#[allow(clippy::all, deprecated, unused_mut)]
mod openrtb_gen {
    include!("generated/openrtb.rs");
}

/// The OpenRTB 2.x package.
pub use com::iabtechlab::openrtb::v2;
pub use json::OpenRtbJson;
